### ISSUE TITLE
template dot notation fails on missing map key in confusing way 

### ISSUE THREAD

**Issue by michalschott** [VirtusLab/render#11]
`templates/resourcequota.yaml`:

```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
spec:
  hard:
    {{- if .resourceQuota.hard.cpu }}
    cpu: {{ .resourceQuota.hard.cpu }}
    {{- else }}
    cpu: "1"
    {{- end}}
```

`ERROR: error (ExecError) evaluating the template named 'templates/resourcequota.yaml': template: templates/resourcequota.yaml:8:25: executing "templates/resourcequota.yaml" at <.resourceQuota.hard....>: map has no entry for key "resourceQuota"`

TODO:
- [x] add `--unsafe-ignore-missing-keys` as a workaround
- [ ] add a dict/map function that will work with default map key option

**Comment by pawelprazak** [comment]
Looks like the root cause is an intended behavior of the go templates with option `"missingkey=error"`, `render` uses this option to make sure we fail fast on any template errors. 

The upstream code is here:
https://golang.org/src/text/template/exec.go?s=19716:19743

The `resourceQuota` is missing and `.resourceQuota.hard.cpu` cannot be evaluated, so the if statement doesn't as we would like to in this case.
This is similar to a "NullPointerException" or "nil panic" when accessing nested field on object/struct that dos not exist.

IMHO the main problem is that the message is confusing.

I'll try to improve the developer experience, something can be done, e.g.:
- adding an additional message if this error occurs with a hint for the template developer
- maybe an existing or custom function can be used to workaround this limitation

**Comment by pawelprazak** [comment]
found a very ugly workaround:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
spec:
  hard:
    {{- if index . "resourceQuota" }}
    {{- if index .resourceQuota "hard" }}
    {{- if index .resourceQuota.hard "cpu" }}
    cpu: {{ .resourceQuota.hard.cpu }}
    {{- end}}
    {{- end}}
    {{- else }}
    cpu: "1"
    {{- end}}
```

**Comment by michalschott** [comment]
How about controlling this behaviour with a CLI flag? `missingkey={zero|error|ignore}`

**Comment by pawelprazak** [comment]
It's one option, but it would be global, using `ignore` makes it consistent with Helm, but is not helpful in catching problems with the template. It will solve one problem but create another.

Actually a simpler workaround is to have always defined keys, e.g.:
```yaml
resourceQuota:
  hard:
    cpu: ""
```

But then you might set the variable as well, and I know it's a bit verbose ;)

So I can add option like `--unsafe-ignore-missing-keys`, this should give the template developer more flexibility, but would make it clear that it's not without consequences.
