### ISSUE TITLE
Replace does not working inside range

### ISSUE THREAD

**Issue by dtelaroli** [VirtusLab/render#32]
It does not work

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  {{- range $i, $value := .Regions }}
  - {{ .AppName }}/{{ $value }}/argo-application.yaml
  {{- end }}
```

```
ERRO[0000] error (ExecError) evaluating the template named 'kustomization.yaml': template: kustomization.yaml:5:7: executing "kustomization.yaml" at <.AppName>: can't evaluate field AppName in type string
```

It is working fine

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  {{- range $i, $value := .Regions }}
  - /{{ $value }}/argo-application.yaml
  {{- end }}
{{ .AppName }}
```
